package com.example.mywebapp.mybatis.model;

import java.util.List;

public class Grupe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.ID
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.KURSAS
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    private Integer kursas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GRUPE.SPECIALYBE
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    private String specialybe;

    private List<Studentas> studentai;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.ID
     *
     * @return the value of PUBLIC.GRUPE.ID
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.ID
     *
     * @param id the value for PUBLIC.GRUPE.ID
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.KURSAS
     *
     * @return the value of PUBLIC.GRUPE.KURSAS
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    public Integer getKursas() {
        return kursas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.KURSAS
     *
     * @param kursas the value for PUBLIC.GRUPE.KURSAS
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    public void setKursas(Integer kursas) {
        this.kursas = kursas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GRUPE.SPECIALYBE
     *
     * @return the value of PUBLIC.GRUPE.SPECIALYBE
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    public String getSpecialybe() {
        return specialybe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GRUPE.SPECIALYBE
     *
     * @param specialybe the value for PUBLIC.GRUPE.SPECIALYBE
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    public void setSpecialybe(String specialybe) {
        this.specialybe = specialybe;
    }

    public List<Studentas> getStudentai() {
        return studentai;
    }

    public void setStudentai(List<Studentas> studentai) {
        this.studentai = studentai;
    }
}