package com.example.mywebapp.mybatis.model;

public class PasirenkamasKursas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASIRENKAMAS_KURSAS.ID
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PASIRENKAMAS_KURSAS.PAVADINIMAS
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    private String pavadinimas;

    private Studentas studentas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASIRENKAMAS_KURSAS.ID
     *
     * @return the value of PUBLIC.PASIRENKAMAS_KURSAS.ID
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASIRENKAMAS_KURSAS.ID
     *
     * @param id the value for PUBLIC.PASIRENKAMAS_KURSAS.ID
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PASIRENKAMAS_KURSAS.PAVADINIMAS
     *
     * @return the value of PUBLIC.PASIRENKAMAS_KURSAS.PAVADINIMAS
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    public String getPavadinimas() {
        return pavadinimas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PASIRENKAMAS_KURSAS.PAVADINIMAS
     *
     * @param pavadinimas the value for PUBLIC.PASIRENKAMAS_KURSAS.PAVADINIMAS
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    public void setPavadinimas(String pavadinimas) {
        this.pavadinimas = pavadinimas;
    }

    public Studentas getStudentas() {
        return studentas;
    }

    public void setStudentas(Studentas studentas) {
        this.studentas = studentas;
    }
}