package com.example.mywebapp.mybatis.dao;

import com.example.mywebapp.mybatis.model.Grupe;
import com.example.mywebapp.mybatis.model.Studentas;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface GrupeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    int insert(Grupe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    Grupe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    List<Grupe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GRUPE
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    int updateByPrimaryKey(Grupe record);

    Grupe selectByNameAndCourse(@Param("specialybe") String specialybe,
                                @Param("kursas") Integer kursas);

    @Results({
            @Result(property = "id", column = "id"),
            @Result(property = "vardas", column = "vardas"),
            @Result(property = "pavarde", column = "pavarde"),

            @Result(property = "grupe.id", column = "grupe_id")
    })
    List<Studentas> selectStudentsByGroupId(@Param("groupId") Integer groupId);
}