package com.example.mywebapp.mybatis.dao;

import com.example.mywebapp.mybatis.model.PasirenkamasKursas;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PasirenkamasKursasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMAS_KURSAS
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMAS_KURSAS
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    int insert(PasirenkamasKursas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMAS_KURSAS
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    PasirenkamasKursas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMAS_KURSAS
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    List<PasirenkamasKursas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PASIRENKAMAS_KURSAS
     *
     * @mbg.generated Mon Mar 31 04:38:57 EEST 2025
     */
    int updateByPrimaryKey(PasirenkamasKursas record);
}