package com.example.mywebapp.mybatis.dao;

import com.example.mywebapp.mybatis.model.PasirenkamasKursas;
import com.example.mywebapp.mybatis.model.Studentas;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StudentasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    int insert(Studentas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    Studentas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    List<Studentas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENTAS
     *
     * @mbg.generated Mon Mar 31 04:38:56 EEST 2025
     */
    int updateByPrimaryKey(Studentas record);

    Studentas selectByNameAndLastName(@Param("vardas") String vardas, @Param("pavarde") String pavarde);

    List<PasirenkamasKursas> selectCoursesByStudentId(@Param("studentId") Integer studentId);

    void insertCourseForStudent(@Param("studentas") Studentas studentas, @Param("course") PasirenkamasKursas course);
}